const { expect } = require("chai");

describe("PrivacyPreservingTransaction", function () {
  it("should verify a valid transaction", async function () {
    const PrivacyPreservingTransaction = await ethers.getContractFactory("PrivacyPreservingTransaction");
    const privacyPreservingTransaction = await PrivacyPreservingTransaction.deploy();
    await privacyPreservingTransaction.deployed();

    // Example proof data (replace with actual proof generated by ZoKrates)
    const a = ["0x...", "0x..."];
    const b = [["0x...", "0x..."], ["0x...", "0x..."]];
    const c = ["0x...", "0x..."];
    const input = ["0x..."];

    expect(await privacyPreservingTransaction.verifyTransaction(a, b, c, input)).to.be.true;
  });
});
